### ISSUE TITLE
README screenshot

### ISSUE THREAD

**Issue by Evizero** [JuliaPlots/RecipesBase.jl#1]
My suggestion is, that a screenshot for the code example in the readme should exist, but not be part of the git repository. For MLDataUtils i do this using a dummy issue to upload the screenshots and then link to them in the readme https://github.com/JuliaML/MLDataUtils.jl/issues/1

**Comment by tbreloff** [comment]
:+1:  Nice idea... as usual!

**Comment by tbreloff** [comment]
Any ideas how we could automatically do something like this for VisualRegressionTests.jl?  Instead of saving a reference image locally, it could upload/download from someplace.

**Comment by Evizero** [comment]
I did think about that possibility briefly but it lead me nowhere. Testing is a tricky thing as we all know. I think the priority should be that the git history has all the information that is needed to run tests. Just think about the mayham of working in different branches or going back in time if the resources needed to test are external.

My best guess is that it should be possible to have representable reference images in like 32x32 nicely downscaled pixels. These don't take that much space. The question is if there is still a sensible threshold for comparing that really differentiates between wrong and right

**Comment by tbreloff** [comment]
I think 32x32 is too small for many tests... minimum is probably closer to 100 or so.  And it should maintain the apsect ratio.  I think we'll just have to play around with those details to get it right.

**Comment by Evizero** [comment]
yes, probably. I am mainly just wishfully bargaining for a size I could happily live with and hoping you agree :)

**Comment by tbreloff** [comment]
Ha.  I mean it would still be better than 99% of graphics packages which have zero tests...

**Comment by tbreloff** [comment]
![tmp](https://cloud.githubusercontent.com/assets/933338/15083906/02a06810-139e-11e6-98a0-dd81c3fb1ad8.png)

**Comment by tbreloff** [comment]
![tmp](https://cloud.githubusercontent.com/assets/933338/15089193/7a453ec6-13cc-11e6-9ae8-959e98b615dc.png)
