### ISSUE TITLE
custom keywords in recipes -- working?

### ISSUE THREAD

**Issue by jverzani** [JuliaPlots/RecipesBase.jl#11]
I don't seem to have success with the example from the README with the keyword custom color. Copy and pasting the code under `pyplot()` produces this error:

```
julia> plot(T(), 5; customcolor = :black, shape=:c)
[Plots.jl] Initializing backend: pyplot
ERROR: Unknown key: customcolor
 in default at /Users/verzani/.julia/v0.4/Plots/src/args.jl:465
 in warnOnUnsupported_args at /Users/verzani/.julia/v0.4/Plots/src/args.jl:757
 in _apply_series_recipe at /Users/verzani/.julia/v0.4/Plots/src/plot.jl:218
 in _plot! at /Users/verzani/.julia/v0.4/Plots/src/plot.jl:537
 in plot at /Users/verzani/.julia/v0.4/Plots/src/plot.jl:52
```

(Under Plots dev and RecipesBase master)

I get a similar error trying to create custom keywords for a different recipe, though as positional arguments they work fine.

**Comment by tbreloff** [comment]
You need a delete!(d, :customcolor) in there. I could update the readme, or
better yet code it so the example works. ;)

**Comment by tbreloff** [comment]
Fixed on master... you should no longer need the `delete!` line.

**Comment by jverzani** [comment]
Thanks. I'm now trying to add a series and think there is another issue. Can you check to see if either I'm doing this incorrectly or there is an issue?

```
@recipe function plot(::T, n = 1; customcolor = :green)

    @series begin # just some series
        seriestype := :scatter
        x := [1,2,3]
        y := [1,3,2]
        ()
    end


    markershape --> :auto          # if markershape is unset, make it :auto
    markercolor :=  customcolor    # force markercolor to be customcolor
    xrotation   --> 45             # if xrotation is unset, make it 45
    zrotation   --> 90             # if zrotation is unset, make it 90

    
    rand(10,n)                     # return the arguments (input data) for the next recipe
end
```

The error I get is 

ERROR: LoadError: Unknown key: customcolor

This is on the just tagged 0.7.3.

**Comment by tbreloff** [comment]
Yeah sorry @jverzani this was a bug that slipped through.  I'm waiting for a new Plots/RecipesBase tag to get merged into METADATA.
