### ISSUE TITLE
How to define grids of subplots without requiring Plots.jl

### ISSUE THREAD

**Issue by aytekinar** [JuliaPlots/RecipesBase.jl#14]
### Description

We would like to require just `RecipesBase.jl` but not `Plots.jl` to have support for subplots.

### Desired Behaviour

We would like to define

```julia
@recipe function f(t::MyType, rows, cols)

  # Some pre-processing to obtain what to plot from `t` based on `rows` and `cols`

  # subplot := true

  @series begin
    subplot := 1
    xdata1, ydata1
  end

  @series begin
    subplot := 2
    xdata2, ydata2
  end
end
```

without requiring the `Plots.jl` package, and still have `plot(t, rows, cols)` give us a 2-subplot plot.

### Actual Behaviour

However, when we read the [comment](https://github.com/tbreloff/Plots.jl/issues/60#issuecomment-219288194) and wrote `subplot := true`, we still had problems when plotting the data unless we used `plot(t, rows, cols, layout = @layout([a; b]))`.

How should we write our recipes to tell `Plots.jl` to plot the series in two (or more) different subplots. Or, even better, to have a grid (such as 2x3) of subplots?

Cc: @neveritt, @cristianrojas

**Comment by tbreloff** [comment]
"layout := (rows,cols)" should be fine. Don't do "subplot := true"... Not
sure where you got that. Layout determines the layout, subplot assigns a
series to a subplot index.

**Comment by aytekinar** [comment]
Thanks for your prompt answer! Yes, that solution works as I wanted it to be.

As for the `subplot := true` method, I was just reading the comment I referenced in my original post, which you defined on May 15, which reads under the **Rules**

> there will be a `subplot` keyword that will accept either a `Subplot` reference(s) or integer(s) representing the subplot index... this way you have full control over which series go to each subplot. Passing a vector could map a series to more than one subplot.

Anyways... Thanks for the `layout = (rows,cols)` tip! :)

**Comment by tbreloff** [comment]
I think you meant to copy this comment:

> For convenience, if you set the subplot keyword but not the layout, it will build a layout for you. If you set subplot=true it will build a layout for you, and also automatically assign series to the subplots in a round-robin fashion (similar to current behavior)

Ok fair enough.  Though you should really trust [the docs](https://juliaplots.github.io/attributes/), and not an old design post in a random issue. ;)

**Comment by pawbz** [comment]
Will I be able to use only `layout := (rows,cols)`?
How can I get additional functionality from `Plots.@layout` and `Plots.grid`?
I need to make layouts, where each subplot has different widths and heights.
Thanks

**Comment by mkborregaard** [comment]
At the moment you need to depend on Plots to use the full layout macro

**Comment by pawbz** [comment]
Thank you, is there any other way that I can design non-regular custom
layout at the moment, without depending on Plots.jl?

**Comment by mkborregaard** [comment]
No, sorry. The layout macro is the final important thing we haven't been able to abstract to RecipesBase.

**Comment by pawbz** [comment]
Thank you! I discovered RecipesBase today and find it a great package.
Adding layout macro would be really helpful! My package cannot depend on
Plots.jl as it can prevent precompilation.

**Comment by mkborregaard** [comment]
Yeah, sorry about that. I think it could be possible to move even more material to RecipesBase, so it's just a question of prioritizing this over the 212 other open issues on Plots.jl :-)
