### ISSUE TITLE
Support for `@layout`

### ISSUE THREAD

**Issue by jw3126** [JuliaPlots/RecipesBase.jl#15]
At the moment, if one wants to specify the `@layout` of a plot in a recipe, one needs to import `Plots`. Would it be possible to get rid of this dependency?

**Comment by ggggggggg** [comment]
I'd also like to use `@layout` in a recipe without depending on `Plots`.

**Comment by ChrisRackauckas** [comment]
See https://github.com/JuliaPlots/RecipesBase.jl/pull/16#issuecomment-299860326

Someone could probably do it, but it would take some effort.

**Comment by ForceBru** [comment]
Any progress on this? Is it maybe possible to somehow emulate the `@layout` macro? Maybe there are some primitives for creating subplots and positioning them? Is it not at all possible to create layouts using only RecipesBase?
