### ISSUE TITLE
Establish a showcase section in readme

### ISSUE THREAD

**Issue by Evizero** [JuliaPlots/RecipesBase.jl#2]
Once we started moving the recipes into LearnBase etc, you should maybe consider creating a section in the readme that links to those code snippets (or otherwise shows them off). Speaking from personal experience, real-life reference implementations often help developers understand how to use something much better than dummy examples

**Comment by Evizero** [comment]
actually I now realise that I got this idea from your readme anyway. so it seems that is your plan all along. anyhow, good idea nonetheless. I wonder what the best way would be to present such a gallery. Readme vs readthedocs?

**Comment by ChrisRackauckas** [comment]
This should link to the ecosystem page.
