### ISSUE TITLE
Enforcing plot order of series

### ISSUE THREAD

**Issue by martinbiel** [JuliaPlots/RecipesBase.jl#25]
When the application of a recipe involves multiple recursive passes in the pipeline, it does not seem possible to enforce a plot order. Below is an easy example:
```
using RecipesBase

struct T end

@recipe function f(t::T)
    s1 = Plots.Shape([0.2,0.4,0.4,0.2,0.2],[0.2,0.2,0.4,0.4,0.2])
    s2 = Plots.Shape([0.5,0.6,0.6,0.5,0.5],[0.5,0.5,0.6,0.6,0.5])
    line = [0.2,0.6]
    @series begin
        seriestype := :shape
        [s1,s2]
    end
    @series begin
        seriestype := :line
        line,line
    end
end
```
A call to `plot(T())` yields:
[result.pdf](https://github.com/JuliaPlots/RecipesBase.jl/files/1223034/result.pdf)
The preferred result would be that the line is drawn last since that series was added last. If I manually unroll the first pipeline step of the shape series:
```
@recipe function f(t::T)
    line = [0.2,0.6]
    @series begin
        seriestype := :shape
        [0.2,0.4,0.4,0.2,0.2,NaN,0.5,0.6,0.6,0.5,0.5],[0.2,0.2,0.4,0.4,0.2,NaN,0.5,0.5,0.6,0.6,0.5]
    end
    @series begin
        seriestype := :line
        line,line
    end
end
```
The result is what I would expect from the recipe:
[result_2.pdf](https://github.com/JuliaPlots/RecipesBase.jl/files/1223046/result_2.pdf)

Is it possible to enforce the plot order within a recipe? I found a hacky way that involves overriding `:series_plotindex` in the pipeline, but it only works with PyPlot which has a `zorder` attribute. 

If it is not possible to enforce through keywords in the recipe, my suggestion is that the pipeline could parse recipes depth-first rather than breadth-first. I.e. use a stack instead of a queue in the [_process_userrecipes](https://github.com/JuliaPlots/Plots.jl/blob/master/src/pipeline.jl#L58) function. This works for me locally, but I do not know if it would be a breaking change or if it would lead to large inefficiencies.

**Comment by mkborregaard** [comment]
It would change the plot order of all existing recipes. I don't have an overview of how many places this matters, though. Could you make a PR with what you have working locally and we will test it out?

But can I ask you, what is wrong with doing it the second way (what you call manually unrolling)? It seems to me that most recipes would look more like that.

**Comment by martinbiel** [comment]
I guess it would mostly matter when extending some existing complex recipe. Say:
```
@recipe function f(sol::AbstractTimeseriesSolution,v::AbstractVector)
    @assert length(sol) == length(v)
    @series begin
        sol
    end
    @series begin
        sol.t,v
    end
end
```
where a call like `plot(sol,sol+0.1*(2*rand(length(sol))-1))` again does not plot the series in the order given in the recipe:
[result.pdf](https://github.com/JuliaPlots/RecipesBase.jl/files/1225209/result.pdf)
The corresponding fix as above, i.e. doing the first level of work in the pipeline for AbstractTimeseriesSolution, would require me to copy in the full recipe code from DiffEqBase. Not ideal.

However, combination recipes where plot order matters might not be common enough to warrant a change in the pipeline. For these simple cases a much easier solution is 
```
function RecipesBase.plot(sol::AbstractTimeseriesSolution,v:AbstractVector)
    plot(sol)
    plot!(sol.t,v)
end
```
I can probably find other workarounds in my own plot recipes as well.

**Comment by mkborregaard** [comment]
I do think it is important that the user has control of the layering of series in the recipe. Could you PR the fix and I'll have a look?

**Comment by martinbiel** [comment]
I made a PR in [Plots](https://github.com/JuliaPlots/Plots.jl/pull/1011)
