### ISSUE TITLE
List of keyword arguments in plot recipe definition

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/RecipesBase.jl#41]
I am not sure what is happening, isn't this a valid function definition?

```julia
using RecipesBase

@userplot FooPlot

@recipe function f(fp::FooPlot; a=1, b=2, kwargs...)
  # SKIP
end
```
It gives me the error:

>BoundsError: attempt to access 1-element Array{Any,1} at index [2]

What am I doing wrong?

**Comment by juliohm** [comment]
As @ChrisRackauckas commented in StackOverflow, I think this is not permitted syntax. I will close the issue and reopen a new one in Makie.jl

**Comment by mkborregaard** [comment]
What would be the purpose of this syntax? Recipes will normally pass on extra keyword args automagically. Could you give a use case?

**Comment by juliohm** [comment]
Thanks @mkborregaard , the use case is very simple, but maybe you have a better way of achieving the same goal. I have this recipe that introduces two new keyword arguments `tmin` and `tmax`. Besides these two keyword arguments, I would like to be able to pass a long list of other keyword arguments forward to the function `voxelreuse`, which is called inside of the recipe:

https://github.com/juliohm/ImageQuilting.jl/blob/master/src/plot_recipes.jl

Right now, I am only calling `voxelreuse` with `nreal=nreal` as a keyword argument, but there are plenty of other parameters that could be passed to it. I am considering writing the parameters one by one, but if there is a more elegant way of avoiding this code repetition, please let me know.

**Comment by mkborregaard** [comment]
Oh, I see. Could you pass in a `TPLconfig` object, or a `Dict` and splat it there?

**Comment by juliohm** [comment]
Thanks, I could do it as well, but I think I will just select the keyword arguments I care the most and forward them explicitly for now. I appreciate the feedback :blush:
