### ISSUE TITLE
Getting "type RecipeData has no field d" error

### ISSUE THREAD

**Issue by giordano** [JuliaPlots/RecipesBase.jl#49]
Tests for latest version of `Measurements.jl` are failing on Julia 1.0 and nightly (package version v0.6.0) with the following error:
```
type RecipeData has no field d
```
Full log at: https://travis-ci.org/JuliaPhysics/Measurements.jl/jobs/422781406.  These are the plot recipes defined by the package: https://github.com/JuliaPhysics/Measurements.jl/blob/5845e18739838d6cd1e76f9a7851502dee71927d/src/plot-recipes.jl

In https://github.com/JuliaLang/METADATA.jl/pull/17434 it's said that this failure is expected, but still I have no idea how to deal with this: just waiting or is there anything I have to do?

**Comment by giordano** [comment]
Bump

**Comment by tkoolen** [comment]
Looks like `plotattributes` replaced `d`. Ref #29, #47.

**Comment by giordano** [comment]
But what is `d`?  There is no explicit `d` in [recipes](https://github.com/JuliaPhysics/Measurements.jl/blob/5845e18739838d6cd1e76f9a7851502dee71927d/src/plot-recipes.jl).

**Comment by tkoolen** [comment]
But there is here: https://github.com/JuliaPhysics/Measurements.jl/blob/5845e18739838d6cd1e76f9a7851502dee71927d/test/plots.jl#L7. Fixed in https://github.com/JuliaPhysics/Measurements.jl/pull/22.

**Comment by mkborregaard** [comment]
Thank you @tkoolen !
