### ISSUE TITLE
Move definition of Shape here?

### ISSUE THREAD

**Issue by chethega** [JuliaPlots/RecipesBase.jl#51]
I'd like to use `Shape` in recipes: I need to draw some polygons (basically for custom error bars), and don't want to incur `Plots.jl` as a dependency for users that don't actually want to plot. Unfortunately, the `Shape` struct is currently defined in `Plots.jl`.

Can we move the definition here?

**Comment by mkborregaard** [comment]
You don't have to - simply set `seriestype := :shape` in your recipe.

**Comment by dlfivefifty** [comment]
I had some old code using `Shape` that's broken:
```julia
@recipe function f(σ::Partition)
    legend --> false
    ratio --> 1.0
    axis --> false
    grid --> false

    ret = Shape[]
    m = length(σ)
    for j = 1:m, k = 1:σ[j]
        push!(ret, Shape([k-1,k-1,k,k],[1-j,-j,-j,1-j]))
    end
    ret
end
```
Any hints how to change it to `seriestype := :shape`?

**Comment by BeastyBlacksmith** [comment]
Would be easier with a MWE, but essentially you take the first argument of `Shape` as x-values, the second as y-values and then set `seriestype = :shape` and then one series per shape as far as I can see.
