### ISSUE TITLE
UnitfulRecipes.jl and AIBECS.jl

### ISSUE THREAD

**Issue by briochemc** [JuliaPlots/RecipesBase.jl#59]
You may already be aware and I'm not sure if this is the right place to do it but here are two packages with some recipes. I thought I should let you know since you ask for it in the readme and a little visibility never hurts...
- @jw3126 created [UnitfulRecipes.jl](https://github.com/jw3126/UnitfulRecipes.jl) (and I have been contributing very recently) to plot data with units ([Unitful.jl](https://github.com/PainterQubits/Unitful.jl)). It essentially strips units from the data and puts them in axis labels. It looks like [this](https://jw3126.github.io/UnitfulRecipes.jl/dev/examples/1_Examples/) and we also show some [Plots examples](https://jw3126.github.io/UnitfulRecipes.jl/dev/examples/2_Plots/) in the docs.
- I also have a few recipes my [AIBECS.jl](https://github.com/briochemc/AIBECS.jl) package for marine biogeochemistry modeling and the plots look like [this](https://briochemc.github.io/AIBECS.jl/stable/howtos/2_plot/) and [this](https://briochemc.github.io/AIBECS.jl/stable/howtos/3_cruiseplot/).

Of course, any input — positive or not — is welcome!

**Comment by mkborregaard** [comment]
I think the best place to make this is as a PR to the examples page on PlotDocs? This page https://docs.juliaplots.org/latest/ecosystem/ (source at https://github.com/JuliaPlots/PlotDocs.jl/blob/master/docs/src/ecosystem.md ) is the obvious place, sadly is in bad need of updating

**Comment by briochemc** [comment]
Oh I see thanks for the info I missed that...
