### ISSUE TITLE
Series recipes

### ISSUE THREAD

**Issue by tbreloff** [JuliaPlots/RecipesBase.jl#6]
Copied from a Plots issue:

FYI: I intend to support (at least) 2 different forms of recipes:

The currently implemented recipe is a converter from user data into Plots-compatible data and attributes. This is great for DataFrames, Distributions or other custom types that are external to base julia.

Internally in Plots, I have a different type of recipe which I have been referring to as a "series recipe" (name suggestions please!! this is what makes quiver, etc). This type of recipe accepts Plots-compatible data and attributes, then rebuilds a new series (or multiple series) to represent a visualization using component parts.

I intend to make this "series recipe" concept available as well, so that things like boxplot, quiver, etc can be moved to external packages and there's no need to have references to the recipe scattered throughout the code. It'll be easier to define custom series types on the fly, and things like the mathematica plot you gave are just a matter of making a quiver plot with more lines/arrows.

**Comment by tbreloff** [comment]
Ref: https://github.com/tbreloff/Plots.jl/issues/240

**Comment by tbreloff** [comment]
One thing that I think would help:  a `register_series_recipe` method, which takes a user definition of a transformation, and maintains a map of component dependencies.

A `violin` recipe depends on the backend supporting the `shape` type, whereas errorbars depend on `path` and `scatter`.  So we'd have:

```julia
const _seriestype_deps = KW(
    :violin => [:shape],
    :xerror => [:path, :scatter],
    ...
)

function register_series_type(transformation_function::Function, name::Symbol, deps::Vector{Symbol})
    ...
end
```

Then I could re-code the supported checks to recursively check that underlying dependencies are filled, and so we wouldn't have to add all these random recipes to the individual backends' supported lists.  And... we'd have a hook to define series types externally.

**Comment by tbreloff** [comment]
Right now I'm working through a reorganization that would put recipes as first-class citizens in Plots land, and I'd like for one macro to enable several different operations:

- Data splits: plot(rand(10,2)) should be broken into 2 series
- User types: plot(MyType()) should apply a recipe and get back a list of series args
- Series recipes: violin(rand(10,2)) should apply a recipe to get back a shape series (but processed after the matrix is split up by step 1)

I think the recipe macro should be adjusted to:

- [ ] automatically (recursively) apply recipes to unprocessed args: `@recipe f(::MyType, args...) = ...`
- [ ] process the args and add them to the dict(s)
- [ ] return a list of KW dicts
- [ ] add some shorthand for creating multiple series:

```julia
@recipe function f(::MyType, args...)
  :linecolor --> :blue
  SERIES begin
    :linetype --> :path
    :x --> d[:x]+100
  end
  SERIES
    :linetype --> :scatter
  end
end
```

An example of how this will help... graphs are composed of a scatter series and a path series.  We don't have to worry about making every arg a 1x2 Matrix{Any} in order to get it to be applied to the correct series.

**Comment by Evizero** [comment]
The series syntax seems a bit arbitrary and awkward. Do you thing a nested macro would work? It would be more relatable I think

```julia
@recipe function f(::MyType, args...)
  :linecolor --> :blue
  @series begin
    :linetype --> :path
    :x --> d[:x]+100
  end
  @series begin
    :linetype --> :scatter
  end
end
```

**Comment by tbreloff** [comment]
I agree... if I can make it work the macro version is better.  

Side question... Any idea how I can allow `linecolor --> :blue` instead of `:linecolor --> :blue`?  I couldn't figure out the right way to do that.

**Comment by tbreloff** [comment]
Actually, I think I can figure out both of those... here's the AST for a toy problem:

```julia
julia> dump(:(
       function f()
           @inner begin
               line --> :blue
           end
       end
       ),20)
Expr 
  head: Symbol function
  args: Array(Any,(2,))
    1: Expr 
      head: Symbol call
      args: Array(Any,(1,))
        1: Symbol f
      typ: Any
    2: Expr 
      head: Symbol block
      args: Array(Any,(2,))
        1: LineNumberNode 
          file: Symbol none
          line: Int64 3
        2: Expr 
          head: Symbol macrocall
          args: Array(Any,(2,))
            1: Symbol @inner
            2: Expr 
              head: Symbol block
              args: Array(Any,(2,))
                1: LineNumberNode 
                  file: Symbol none
                  line: Int64 4
                2: Expr 
                  head: Symbol -->
                  args: Array(Any,(2,))
                    1: Symbol line
                    2: QuoteNode 
                      value: Symbol blue
                  typ: Any
              typ: Any
          typ: Any
      typ: Any
  typ: Any
```

**Comment by tbreloff** [comment]
Still thinking out loud... it might be helpful to have a new type representing "data with attributes" (name ideas welcome).  Just a simple wrapper around an argument list, and a KW dict, but it could enable some nice conveniences, like a getindex that can pass through to the KW, unless it's x/y/z in which case it could grab an arg.  I think that could be designed so that reading is unchanged but the separation between the data and how the data is displayed is stronger.

```
d[:linetype] # really d.kw[:linetype]
d[:x]     # really d.data[1] or something similar
```

**Comment by tbreloff** [comment]
See https://github.com/tbreloff/Plots.jl/issues/254 for some good discussion/description of recipes...

**Comment by tbreloff** [comment]
I've come a long way with this concept.  I've replaced much of the internal pipeline (steps 3 through 8 in the [docs](http://plots.readthedocs.io/en/latest/pipeline/) with a core dependency on the recipe mechanic.  Recipes are applied recursively until all inputs are fully processed, then defaults are added, along with a few other things, and then the series are recursively processed as "series recipes", where the differing expectations are:

- the first arg is a Val type, and you can dispatch on x/y/z:  `@recipe f(::Type{Val{:mycustomseriestype}}, x, y, z) = ...`
- you should force the linetype to something else, otherwise you'l have infinite recursion: `d[:linetype] = :shape`
- return args are ignored... only the KW dict is manipulated

Most of the tests are working now (pretty much everything that's not a subplot), and I started with the boxplot recipe which seems to work.  I need to convert the other series recipes to RecipesBase (pretty easy) and add some tests for this stuff.

Soon the only remaining items will be:

- [ ] properly handling strings as input data (and generally handling discrete axes)
- [ ] [subplots](https://github.com/tbreloff/Plots.jl/issues/60)

**Comment by tbreloff** [comment]
See: https://github.com/tbreloff/Plots.jl/issues/60#issuecomment-219288194 regarding subplots
