### ISSUE TITLE
Fix duplicate "Type recipe" section in the docs?

### ISSUE THREAD

**Issue by briochemc** [JuliaPlots/RecipesBase.jl#66]
This might be on purpose but I found it confusing... These two sections could be merged into a single one, right? I mean this one:
http://juliaplots.org/RecipesBase.jl/stable/types/#Type-Recipes-1
and that one: 
http://juliaplots.org/RecipesBase.jl/stable/types/#Type-Recipes-2

**EDIT*** Oh I'm just confused, sorry. I see now that the first section is part of the "overview", while the second one goes into details... Maybe move the tip boxes to the detailed sections? Anyway I'll close this...

**Comment by daschw** [comment]
I see. Let me know if you have a suggestion to make it less confusing.

**Comment by briochemc** [comment]
Ha sure! 

I started trying to rewrite some bits, but then it opened a bit of a pandora's box, so I just gave up when I realized it was going to become a huge time sink. I kept my progress locally though and might come back to it, but keep your expectations very low 😅
