### ISSUE TITLE
Cannot set annotation font style without Plots dependency

### ISSUE THREAD

**Issue by anowacki** [JuliaPlots/RecipesBase.jl#72]
This is a long-standing issue (e.g., see [here](https://discourse.julialang.org/t/adding-annotations-with-custom-font-and-color-in-plot-recipes/4740)), but one I still bump up against, though I can't find a specific issue here or in Plots for it.

I would like to be able to define the format (family, size, colour, etc.) of series annotations in recipes (with `series_annotations`), but I do not want to depend on Plots, and this is currently impossible.  There is currently no way to set these properties without using `Plots.text` and thereby `Plots.font`.  The fix for https://github.com/JuliaPlots/Plots.jl/issues/555 (https://github.com/JuliaPlots/Plots.jl/commit/f2e2ffa17033145d06166db217b39ce3a45a02a1) now allows one to use recipes to set font attributes for labels, but not annotations on plots themselves.  [The workaround here](https://discourse.julialang.org/t/adding-annotations-with-custom-font-and-color-in-plot-recipes/4740/5?u=anowacki) does not work in all cases—for instance when the calling module has loaded `Plots`, but not in to `Main`—and is pretty brittle in any case.

Though I don't much understand RecipesBase or Plots internals, for me as a user it would make sense to set attributes similar those introduced by https://github.com/JuliaPlots/Plots.jl/commit/f2e2ffa17033145d06166db217b39ce3a45a02a1, and in recipes use (for example) `:annotfontfamily`, `:annotfontsize` and so on to set annotation font parameters.

**Comment by mkborregaard** [comment]
This commit: https://github.com/JuliaPlots/Plots.jl/commit/7acb5a4bdb0497877b4d214c0cc1a05a8d9bfcf7 was intended to fix this, allowing passing a tuple instead to annotations. I know for a fact that it used to work, but something might have changed.

**Comment by mkborregaard** [comment]
So this works
```julia
struct MyType end
@recipe function f(x::MyType)
       annotations := (2, 4, ( "test", :right, 20))
       1:10, 1:10
end
plot(MyType())

**Comment by BeastyBlacksmith** [comment]
Might be relevant: https://github.com/JuliaPlots/Plots.jl/pull/3463

**Comment by anowacki** [comment]
Thank very much!  I hadn't realised that passing tuples was possible, and this solves my issue.

When time allows I'll submit a PR to add this to the docs (specifically the attributes list [here](http://docs.juliaplots.org/latest/generated/attributes_subplot/#Subplot) and [here](http://docs.juliaplots.org/latest/generated/gr/#gr-ref20) for each backend).  I can't find this mentioned anywhere and so I think that's why I hadn't realised it could be done.
