### ISSUE TITLE
Documentation about testing

### ISSUE THREAD

**Issue by guilhermebodin** [JuliaPlots/RecipesBase.jl#78]
Ia there a good / correct way to test recipes inside your package?

**Comment by mkborregaard** [comment]
The easiest is probably to run the `apply_recipe` function on your data, then compare the resulting PlotAttributes object to a reference. There's an example here https://github.com/JuliaPhysics/Measurements.jl/blob/master/test/plots.jl

**Comment by guilhermebodin** [comment]
Thanks!
