### ISSUE TITLE
Only `annotations` in last series are plotted; others are ignored

### ISSUE THREAD

**Issue by anowacki** [JuliaPlots/RecipesBase.jl#81]
It appears to me that in recipes, `annotations` are ignored, unless they are in the last series in the recipe.  For example:

```
using RecipesBase, Plots

if !@isdefined(A)
    struct A end
end

@recipe function f(a::A)
    xlims := (0, 1)
    ylims := (0, 1)
    seriestype := :scatter
    @series begin
        annotations := [(0.3, 0.3, ("A", :blue))]
        [0.25], [0.25]
    end
    @series begin
        annotations := [(0.8, 0.8, ("B", :red))]
        [0.75], [0.75]
    end
end

plot(A())
```

produces

![noA](https://user-images.githubusercontent.com/1231209/125427519-bf763a3c-2715-4cd2-9aaf-dbeef59f958a.png)

Note that only the second annotation ("B") is plotted and the first ignored.

If instead we remove the second assignation to `annotations`, we get no annotations at all!

```julia
@recipe function f(a::A)
    xlims := (0, 1)
    ylims := (0, 1)
    seriestype := :scatter
    @series begin
        annotations := [(0.3, 0.3, ("A", :blue))]
        [0.25], [0.25]
    end
    @series begin
        # No `annotations` at all here
        [0.75], [0.75]
    end
end

plot(A())
```

![noAorB](https://user-images.githubusercontent.com/1231209/125427766-ad54942d-d6fc-408c-aa85-e059c1e4587b.png)

I expected this to work, because the equivalent direct calls to Plots' commands does the job fine:

```
scatter([0.25], [0.25], annotations=[(0.3, 0.3, ("A", :blue))], xlims=(0, 1), ylims=(0, 1))
scatter!([0.75], [0.75], annotations=[(0.8, 0.8, ("B", :red))])
```

![AandB](https://user-images.githubusercontent.com/1231209/125428207-a0b1ddd8-d7c4-4165-9c16-07a4d12f1c03.png)

I can work around this by doing a single final series in a recipe with all annotations, but it would be nice if this wasn't necessary, since it separates out the annotations from the data that are being plotted in each series in the recipe.

**Comment by BeastyBlacksmith** [comment]
The issue here is, that `annotations` is a subplot attribute and not a series attribute. This should work better with `series_attributes` or if you really want to have it close to the series you could do
```julia
@recipe function f(a::A)
           xlims := (0, 1)
           ylims := (0, 1)
           seriestype := :scatter
           anns = plotattributes[:annotations] = []
           @series begin
               push!(anns, (0.3, 0.3, ("A", :blue)))
               [0.25], [0.25]
           end
           @series begin
               push!(anns, (0.8, 0.8, ("B", :red)))
               [0.75], [0.75]
           end
end
```
