### ISSUE TITLE
Docs are not deployed

### ISSUE THREAD

**Issue by sostock** [JuliaPlots/RecipesBase.jl#87]
The latest version of the package is v1.2.1, but the documentation is only available for v1.1.1 or older.

**Comment by BeastyBlacksmith** [comment]
I migrated the documentation from travis to gh-actions. It won't build for the missing tags, but documentation didn't change anyways. The `dev` version is now up-to-date.

Thanks for reporting.

**Comment by hyrodium** [comment]
>It won't build for the missing tags,

I'm not sure we need to reopen this issue, but Documenter.jl can deploy docs with a tag such as `v1.2.1+doc1`.

https://juliadocs.github.io/Documenter.jl/dev/man/hosting/#Documentation-Versions
